### PR TITLE
add voice Victoria

### PR DESCRIPTION
**Pull request by maniyax**
New female voice.

## what's done

- [x] added to cmake
- [x] github actions builds this voice
- [x] android application supports this voice

## testing performed

- [x] nvda add-on works
- [x] rhvoice-test talks
- [x] android application can download this voice

## other information

this is a first voice which is added as a submodule. and also uses the Github infrastructure to store binary data.

## current problems

when artifacts are automatically created, unnecessary garbage is included in the archive, for example, the .git folder, readme files, etc. this should be fixed soon.

### CODE REVIEW

**Comment by d9k** [comment]
Build error:

```
> scons                                                                                         
scons: Reading SConscript files ...                                                             
Mkdir("build/linux")                                                                            
Checking whether the C compiler works... yes                                                    
Checking whether the C++ compiler works... yes                                                  
Checking for pkg-config... yes                                                                  
Checking for libpulse-simple... no                                                              
Checking for ao... no                                                                           
Checking for portaudio-2.0... no                                                                
('Configuring ', '/home/d9k/repos/RHVoice/src/core/config.h.in', 'into', '/home/d9k/repos/RHVoi$
e/src/core/config.h', '...')                   
('Configuring ', '/home/d9k/repos/RHVoice/src/include/core/config.h.in', 'into', '/home/d9k/rep$
s/RHVoice/src/include/core/config.h', '...')                  
IOError: [Errno 2] No such file or directory: '/home/d9k/repos/RHVoice/data/voices/victoria/voi$
e.info':                                         
  File "/home/d9k/repos/RHVoice/SConstruct", line 370:
    build_for_linux(base_env,vars)          
  File "/home/d9k/repos/RHVoice/SConstruct", line 328:   
    duplicate=0)                                                               
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)                   
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)  
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/home/d9k/repos/RHVoice/data/SConscript", line 42:
    props=RHVoiceInfoParser.parse(subdir.File(type+".info").abspath)
  File "/home/d9k/repos/RHVoice/site_scons/RHVoiceInfoParser.py", line 10:
    with io.open(path,"rt",encoding="utf-8") as f:
```

**Comment by abitrolly** [comment]
I will quote myself. )

> Perhaps `SCons` should restore submodules if they are absent.

https://github.com/RHVoice/RHVoice/issues/258#issuecomment-752546499

**Comment by beqabeqa473** [comment]
information wil be available in docs.

but before that, --recursive flag while cloning or git submodule
update --init after clone.

it is not good practise to do those primitive things, because lots of
projects nowadays and not from now are using submodules, and i never
saw that scons or some other build system restore submodules.

i agree, that there is lack of information, that should be added to
build docs as soon as possible.

On 1/4/21, Anatoli Babenia <notifications@github.com> wrote:
> I will quote myself. )
>
>> Perhaps `SCons` should restore submodules if they are absent.
>
> https://github.com/RHVoice/RHVoice/issues/258#issuecomment-752546499
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/pull/256#issuecomment-753981760


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by abitrolly** [comment]
> i never saw that scons or some other build system restore submodules.

But you can see `gradle` fetch dependencies for Android projects, and `pip` and `go build` fetching and building sources from `git` repos. I don't see why a different build system such as `SCons` can not do the same. It is good to have docs on how to generate new voices instead, and close the boring routine with automation.

**Comment by beqabeqa473** [comment]
it is up to maintainers of course, but personally i don't see much
point to take efforts for that.
git modules are not ekzotic things and adding one argument should not
be a problem at all.

On 1/4/21, Anatoli Babenia <notifications@github.com> wrote:
>> i never saw that scons or some other build system restore submodules.
>
> But you can see `gradle` fetch dependencies for Android projects, and `pip`
> and `go build` fetching and building sources from `git` repos. I don't see
> why a different build system such as `SCons` can not do the same. It is good
> to have docs on how to generate new voices instead, and close the boring
> routine with automation.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/pull/256#issuecomment-753998732


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by abitrolly** [comment]
If the need to take effort is the only argument against `SCons` checking out missing submodules, then could you evaluate how much is that effort? How familiar are you with SCons, by the way?

**Comment by alex19EP** [comment]
I agree with @beqabeqa473 scons shouldn't restore a submodules. but we can add a useful error in case some voices are missing.

**Comment by abitrolly** [comment]
@alex19EP so.. What are your arguments against using scons to fetch these dependencies?

**Comment by alex19EP** [comment]
> 
> 
> @alex19EP so.. What are your arguments against using scons to fetch these dependencies?

I'm sure the build system shouldn't do this. for example, some distributions do not have network access when building.

**Comment by abitrolly** [comment]
@alex19EP "I am sure" is not an argument. The argument here could be rephrased as "SCons should not fetch absent git submodules, because some distributions of RHVoice do not have network access when building". This doesn't make sense to me, because without a network you can't fetching submodules with `git` either. Let me remind as well, that under the hood SCons just going to involve the same operations you would do manually by detecting missing dirs.

**Comment by beqabeqa473** [comment]
hello again.

the only thing here what would be acceptable is to explicitly enable
voices which we need, as it is already with languages, but not to
fetch git modules automatically.

i will repeat, fetching submodules is not a thing which should be done
in buld system.
yes, i understand that this causes error for this time, in this case,
logic should be implemented to skip voices which are not fetched.

On 1/7/21, Anatoli Babenia <notifications@github.com> wrote:
> @alex19EP "I am sure" is not an argument. The argument here could be
> rephrased as "SCons should not fetch absent git submodules, because some
> distributions of RHVoice do not have network access when building". This
> doesn't make sense to me, because without a network you can't fetching
> submodules with `git` either. Let me remind as well, that under the hood
> SCons just going to involve the same operations you would do manually by
> detecting missing dirs.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/pull/256#issuecomment-756012555


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by abitrolly** [comment]
> explicitly enable voices which we need

That counts as an argument. Now the question is - do you want to explicitly enable voices using build config, or you want to control which voices are build by checking out and removing submodules with `git`?

> i will repeat, fetching submodules is not a thing which should be done
in buld system.

It counts as your personal opinion, but being ungrounded it doesn't count as an argument no matter how many times you repeat that.

**Comment by alex19EP** [comment]
> The argument here could be rephrased as "SCons should not fetch absent git submodules, because some distributions of RHVoice do not have network access when building".

yes. let me give an example: look at RHVoice [pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rhvoice-git) in Arch Linux aur.
here we providing necessary srcs and initializing git submodules by hand. so we can create a source archive without calling any build system. do not forget that we have two of them at the moment. I think this is the most correct option, this way we do not complicate the build system.

>> i will repeat, fetching submodules is not a thing which should be done
in buld system.

> It counts as your personal opinion, but being ungrounded it doesn't count as an argument no matter how many times you repeat that.

I already said that the main thing here is to keep it simple and transparent for developers. For example, I never liked it if the build system would download something automatically. here we don't need to do this at all.

**Comment by abitrolly** [comment]
@alex19EP if submodules are present, SCons won't redownload them. I don't see how using SCons prevents Arch Linux packagers from fetching git submodules manually, and why users on other platforms should care about that.

> I already said that the main thing here is to keep it simple and transparent for developers. For example, I never liked it if the build system would download something automatically. here we don't need to do this at all.

You can use `CMake` for developers who like simple manual instructions and leave `SCons` to those who prefer practicality over purity.

**Pull request merged**
