### PR TITLE
Polish language.

### PR DESCRIPTION
**Pull request by grzezlo**
Authors: @grzezlo, @zstanecic, with help of @beqabeqa473.

### CODE REVIEW

**Comment by alex19EP** [comment]
hello @grzezlo can you move language data files to the separate repo and add them as a submodule?
if yes. I will create a new repo under rhvoice namespace for you.

**Comment by grzezlo** [comment]
Hi @alex19EP.
If I understand well, RHVoice languages are not separate submodules, being part of the main repository.
Only the data/voices are separate submodules.
In this pull request, we're providing only language definition for Polish (data/languages/Polish, and src/scripts/Polish).
Some Polish voices are under construction and will be provided separately in near future.
I double checked now, that in the submodules list no data/languages are provided for RHVoice as a separate repositories.

**Comment by zstanecic** [comment]
I agree here, even Russian is not a submodule at all.

**Comment by alex19EP** [comment]
> Hi @alex19EP. If I understand well, RHVoice languages are not separate submodules, being part of the main repository. Only the data/voices are separate submodules.

for now yes. but it will change in future. so why not start doing it correctly, if there is such an opportunity?

**Comment by alex19EP** [comment]
> I agree here, even Russian is not a submodule at all.

yep that should be changed too. see my first reply for motivation.

**Comment by grzezlo** [comment]
Due to lack of new feature's documentation, Polish is not provided as a data-only language (e.g. no idea what tok.eos=true or false means in language configuration, or ph.flags=l). 
The base of the language are cpp and hpp files.
And it's impossible to have submodule occupying few files in subfolders: src/core, src/include.
So, even if we'd convert the Polish language to data-only language, it wouldn't be possible to have it occupy separate folders in RHVoice repo: data/languages/Polish, src/scripts/Polish.
Also, I have no idea about rationale behind such splitting:
1. The submodule in the git sense is a separate library, which can exist as a stand-alone thing, e.g. lib Sonic, which can be reused in many projects.
Language for RHVoice has no sense outside the RHVoice, it's not an independent library or piece of code, it fully depends on the RHVoice engine.
2. Although we're now providing language definition, there is also a question about future voices in separate repositories.
Is placing a bunch of binary files being a RHVoice's voice in the separate github repo a good practice?
Those repos don't contain any source code, only some binaries, not sure if it's not against a github policy to create such binary-only repos?
But not going into the off-topic, please clarify what is expected from us now: how to publish as a single git submodule data/languages/Polish, src/scripts/Polish and some files in src/core and src/include?
Even the Albanian added few days ago exists as part of main repo, so I'm not sure about the status of this "language in separate repo" thing: is it a mature concept, or new innovation idea?

**Comment by alex19EP** [comment]
> Due to lack of new feature's documentation, Polish is not provided as a data-only language (e.g. no idea what tok.eos=true or false means in language configuration, or ph.flags=l). The base of the language are cpp and hpp files. And it's impossible to have submodule occupying few files in subfolders: src/core, src/include. So, even if we'd convert the Polish language to data-only language, it wouldn't be possible to have it occupy separate folders in RHVoice repo: data/languages/Polish, src/scripts/Polish.

yes. I only talking about binary data. scripts and cpp files should be added to this repo.

>Also, I have no idea about rationale behind such splitting:
> 
>     1. The submodule in the git sense is a separate library, which can exist as a stand-alone thing, e.g. lib Sonic, which can be reused in many projects.
>        Language for RHVoice has no sense outside the RHVoice, it's not an independent library or piece of code, it fully depends on the RHVoice engine.

for rationale look at #125 

>     2. Although we're now providing language definition, there is also a question about future voices in separate repositories.
>        Is placing a bunch of binary files being a RHVoice's voice in the separate github repo a good practice?
>        Those repos don't contain any source code, only some binaries, not sure if it's not against a github policy to create such binary-only repos?

I don't think this violates any policy. and yes the voice data must also be added as a submodule.

>        But not going into the off-topic, please clarify what is expected from us now: how to publish as a single git submodule data/languages/Polish, src/scripts/Polish and some files in src/core and src/include?

I will create language repo for you and you just push data files into it. and integrate them as a submodule in this pr.

**Comment by grzezlo** [comment]
Thanks for explanations, I understand that it makes sense for voices repositories, few megabytes each, or even for Albanian language (29 MB of data), but for Polish, 160 kilobytes in total... Ok, but as you wish:)
Thanks for creating the Polish repo, but I can not push there:
remote: Permission to RHVoice/Polish.git denied to grzezlo.

**Comment by alex19EP** [comment]
@grzezlo you need to accept my invite.

**Comment by grzezlo** [comment]
Yes, just accepting. I missed the notification about it, so it's why I deleted my comment.

**Comment by grzezlo** [comment]
Ok, moved data/languages/Polish to new repo included as submodule.
Src/core and src/scripts leaved in this PR.
My question, what about updates now?
As I understand, we'll need to update separately the data/languages/Polish in separate repo, src/scripts/Polish in this repository by pull request, and how to keep both things in sync?

**Comment by zstanecic** [comment]
Can you include me there, as I am also one of the authors?

Best,

Zvonimir

**Comment by alex19EP** [comment]
> how to keep both things in sync?

just update submodule in script and cpp files pr.

@zstanecic will do tomorrow.

**Comment by Olga-Yakovleva** [comment]
I'd like all the new languages from now on to be data-only, unless there is a very good reason against it. Albanian language implementation shows how to do it: define the graphemes in graph.txt, language codes in locale.info, set the data_only flag in language.info, move all the logic, such as stress assignment, into the finite state transducers. Macedonian sources is another example of stress assignment without using C++. If I understand correctly, Macedonian may be similar to Polish in having a default stress pattern and exceptions.

**Comment by Olga-Yakovleva** [comment]
I meant to update the overall structure to support language repositories with sources and data, but still haven't found the time to work on it. But data-only languages can be packaged and updated without recompiling RHVoice, their logic is separate from the C++ core.

**Comment by Olga-Yakovleva** [comment]
Moreover, if RHVoice 1.6 and later finds a data-only language in its data directory, it will loaded without knowing anything about it in advance.

**Comment by grzezlo** [comment]
Thanks @Olga-Yakovleva for the feedback.
I wanted to provide Polish as data-only, but as I wrote in one of previous comment, 24 days ago :
Due to lack of new feature's documentation, Polish is not provided as a data-only language (e.g. no idea what tok.eos=true or false means in language configuration, or ph.flags=l).
Having the idea what to set there, I can of course convert Polish to data-only.
At the moment i don't bothered with stress calculations, the sylabification also is taken from some language where it was implemented as simple as possible.
The goal at the moment is to have working Polish language, and some good quality voice, we would work on the improvements of the language definitions in next version if it really would have any impact on the speech quality to improve sylabification, stress calculations, or gpos.

**Comment by Olga-Yakovleva** [comment]
OK. I just meant that I would only merge a data-only language into 
master. As for those other configuration flags you mentioned, they are 
optional. For example, if you set tok.eos=true, the tokenizer will 
receive a tok symbol at the end of input if this token ends a sentence. 
If such flags aren't used, they are assumed to be false and RHVoice will 
follow its default behaviour.

**Comment by grzezlo** [comment]
Thanks for the larification.
I'll convert Polish to data-only and push it in this PR.

**Comment by grzezlo** [comment]
Done. Polish is now a data-only language.

**Comment by zstanecic** [comment]
Hi! After converting polish to data only, we have lost the inntonation patterns defined by pitch-mod.dt. Namely exclamation sentences and questions in general are broken. 
In the core registration code, we had:
  void polish::post_lex(utterance& u) const
  {
    relation& sylstruct_rel=u.get_relation("SylStructure");
    for(relation::iterator word_iter(sylstruct_rel.begin());word_iter!=sylstruct_rel.end();++word_iter)
      {
        item& last_syl=word_iter->last_child();
        if(last_syl.has_prev())
          last_syl.prev().set<std::string>("stress","1");
        else
          last_syl.set<std::string>("stress","1");
      }
  }
}
How to write this using decision tree or foma?
@Olga-Yakovleva

**Comment by zstanecic** [comment]
Note that this thing mentioned above worked on any exclamation and interrogative sentence, i.,e anything that ends with ! or ? had the different intonations, respectively.

**Pull request merged**
