### PR TITLE
Use 1.10.0 core in SAPI builds.

### PR DESCRIPTION
**Pull request by Olga-Yakovleva**

### CODE REVIEW

**Comment by Olga-Yakovleva** [comment]
@zstanecic, could you please test?

**Comment by Olga-Yakovleva** [comment]
And this is the release candidate for the addon: https://rhvoice.org/download/RHVoice-1.10.0.nvda-addon

**Comment by beqabeqa473** [comment]
Out of curiosity, are there any changes in core?
I didn't see commits about that..

On 10/23/22, Olga Yakovleva ***@***.***> wrote:
> And this is the release candidate for the addon:
> https://rhvoice.org/download/RHVoice-1.10.0.nvda-addon
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/pull/657#issuecomment-1288093091
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by zstanecic** [comment]
Hi,

Yes, there are changes in core:

Mage replacement and emoji.cpp list update.

**Pull request merged**
