### PR TITLE
Separate Python binding

### PR DESCRIPTION
**Pull request by techtonik**
This makes it possible to use RHVoice through Python without NVDA plugin.

https://pypi.python.org/pypi/RHVoice

### CODE REVIEW

**Comment by zstanecic** [comment]
чего доброго приносит это изменение в коде?

W dniu 24.02.2016 o 15:05, anatoly techtonik pisze:

**Comment by techtonik** [comment]
It makes it possible to use RHVoice with standard Python installation.

**Comment by zstanecic** [comment]
почему ты пишешь по-английски?
я по-русски понимаю.
W dniu 24.02.2016 o 15:19, anatoly techtonik pisze:

**Comment by techtonik** [comment]
@zstanecic it is not for you, it is for people who are interested in Python bindings for RHVoice, most of whom don't know Russian.

**Comment by zstanecic** [comment]
а ты мыслил о том, что бы дать это как пул риквест?

W dniu 24.02.2016 o 17:04, anatoly techtonik pisze:

**Comment by beqabeqa473** [comment]
@zstanecic, please don't say things which you don't know.
first of all, anatoliy made it as a pull request.
secondly, don't spam feed with stupid comments.
it seems, you don't know anything about this thread, so, give up.

On 2/24/16, zstanecic <notifications@github.com> wrote:
> а ты мыслил о том, что бы дать это как пул риквест?
>
> W dniu 24.02.2016 o 17:04, anatoly techtonik pisze:
>>
>> @zstanecic <https://github.com/zstanecic> it is not for you, it is for
>> people who are interested in Python bindings for RHVoice, most of whom
>> don't know Russian.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Olga-Yakovleva/RHVoice/pull/34#issuecomment-188321559>.
>>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/pull/34#issuecomment-188344854


-- 
with best regards beqa

**Comment by techtonik** [comment]
@beqabeqa473 take it easy, the guy just joined Github and can't see all the features over email.

**Comment by alex19EP** [comment]
hello @techtonik can you fix conflicts?

**Comment by dmikushin** [comment]
Here is a rather "mechanical" re-apply of PR #34 by @techtonik , which is yet to be tested thoughtfully: https://github.com/Olga-Yakovleva/RHVoice/pull/158 Few patches do not move over some of the recently added `try ... catch` blocks - this has to be re-visited.

**Comment by techtonik** [comment]
Hi. I rebased the PR towards the master, but I have no idea if that still works.

**Comment by dmikushin** [comment]
Shall we maybe add Python standard units tests? That would do a great coverage for the native code as well.

**Comment by techtonik** [comment]
I wrote a simple script for bisecting why this PR crashes. That's all I can do for now. And I don't work with Windoze anymore.

**Comment by techtonik** [comment]
The problematic part is `mbcs` encoding added in a1785c45a0070591d38a352c13e1c71863bbb1d3 by @beqabeqa473. The encoding is absent on Linux. And I don't understand the reason for replacing `sys.getfilesystemencoding()` with hardcoded value.

**Comment by techtonik** [comment]
If you can test on Windows + Python 2 / Python 3, we can just change it to `sys.getfilesystemencoding()` and check.

**Comment by techtonik** [comment]
Did some tests with AppVeyor.

```sh
echo --- Python 2 on Windows ---
py -2 -c "import sys; print('sys.getfilesystemencoding() - ' + sys.getfilesystemencoding())"
sys.getfilesystemencoding() - mbcs
echo --- Python 3 on Windows ---
--- Python 3 on Windows ---
py -3 -c "import sys; print('sys.getfilesystemencoding() - ' + sys.getfilesystemencoding())"
sys.getfilesystemencoding() - utf-8
```

**Comment by techtonik** [comment]
Previous rebase was not on top. Rebased again. =)

**Comment by techtonik** [comment]
Bisecting to find out when it broke.
```
git bisect start
git bisect bad
git bisect good upstream/master
git bisect run ./src/nvda-synthDriver/testpython.sh
```
```
+ python2 /home/techtonik/p/RHVoice/src/nvda-synthDriver/RHVoice.py 'this is a test phrase from Python 2'
Traceback (most recent call last):
  File "/home/techtonik/p/RHVoice/src/nvda-synthDriver/RHVoice.py", line 37, in <module>
    module_dir=os.path.dirname(__file__.decode("mbcs"))
LookupError: unknown encoding: mbcs
64f951548b70d3cc9f8429140a4f225a79219d7c is the first bad commit
```

`./src/nvda-synthDriver/testpython.sh` script.
```
#!/bin/bash

set -o errexit
set -o xtrace

# https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

python2 "$DIR"/RHVoice.py "this is a test phrase from Python 2"
python3 "$DIR"/RHVoice.py "this is a test phrase from Python 3"
```

**Comment by techtonik** [comment]
Rebased and pushed to fix `TabError: inconsistent use of tabs and spaces in indentation`.

**Comment by alex19EP** [comment]
ok. @techtonik i tryed to rebace it on latest master but looks like. i haven't push access to your branch.

can you do that?

**Comment by beqabeqa473** [comment]
Hello all.

I think some things should be changed here.

In the current code, there are fragments which ar not needed for nvda synth driver.

so, i think, python wrapper and CLI should be separated as well and nvda synth driver, as well as python CLI should use one shared wrapper, so we can omit CLI part when building NVDA-addon

**Comment by techtonik** [comment]
@alex19EP rebasing this codebase is a pain. I do it as an exercise to polish my workflow, but it usually takes a few hours to push commits over the conflicting changes to at least ensure that nothing changed.

@beqabeqa473 what are benefits of dropping the code that is useful for debugging and doesn't require additional dependencies?

**Comment by beqabeqa473** [comment]
CLI can be distributed as an example, but not as part of a wrapper.
personally for me, it is not so accurate

On 12/27/20, anatoly techtonik <notifications@github.com> wrote:
> @alex19EP rebasing this codebase is a pain. I do it as an exercise to polish
> my workflow, but it usually takes a few hours to push commits over the
> conflicting changes to at least ensure that nothing changed.
>
> @beqabeqa473 what are benefits of dropping the code that is useful for
> debugging and doesn't require additional dependencies?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/pull/34#issuecomment-751445723


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by techtonik** [comment]
@beqabeqa473 reminds me the anecdote about "not so accurate". =) If you want to split the package and maintain parity between CLI and wrapper through versioning, packaging and changelogs, I won't stop you. Although I support the part of zen of Python that says that practicality beats purity.

What will be really helpful is checking if the PR works on your machine, which I suppose is Windows with NVDA. Because I am on Linux with `terminal`, and the CLI is the only way for me test the changes here.

**Pull request closed without merging**
