### PR TITLE
add Evgeniy voices

### PR DESCRIPTION
**Pull request by maniyax**
Add new russian and english male voices.

### CODE REVIEW

**Comment by maniyax** [comment]
Hi!

Merge this PR please.

**Comment by alex19EP** [comment]
> 
> 
> Hi!
> 
> Merge this PR please.

I need to find some free time for this. I remember about it.

**Comment by maniyax** [comment]
> All checks have passed
> 8 successful and 1 neutral checks

What is stopping you from doing it now?

**Comment by alex19EP** [comment]
> 
> 
> > All checks have passed
> > 8 successful and 1 neutral checks
> 
> What is stopping you from doing it now?

it need's to be added in android application.

**Comment by maniyax** [comment]
> it need's to be added in android application.

> CI / Android build (pull_request) Successful in 8m

Users want APK-file with Evgeniy.

**Comment by maniyax** [comment]
I may not understand technical details, but it didn't cause much trouble before.

**Comment by alex19EP** [comment]
> 
> 
> > it need's to be added in android application.
> 
> > CI / Android build (pull_request) Successful in 8m

it builds app withe out this voice. until you make edits to the java code, this will not work.
for example look at: d80d5d8538a6a8f5f85507979a3a863b2bd8f3d0

> 
> Users want APK-file with Evgeniy.

I kno it. and I need free time for making it happen, sorry.

**Pull request merged**
