### PR TITLE
Separate Python binding

### PR DESCRIPTION
**Pull request by dmikushin**
Make it possible to use RHVoice through Python without NVDA plugin.

https://pypi.python.org/pypi/RHVoice

This is a rather "mechanical" re-apply of PR https://github.com/Olga-Yakovleva/RHVoice/pull/34 by @techtonik , which is yet to be tested thoughtfully. Also, few patches do not move over some of the recently added try..catch blocks - this has to be re-visited.

### CODE REVIEW

**Comment by techtonik** [comment]
Can you rebase it against `master` to see how it is diverted?

**Comment by dmikushin** [comment]
Hi @techtonik sorry what do mean? As I can see, currently there is no conflict with the current master.

**Comment by techtonik** [comment]
Nevermind. I just wanted to compare the results of the rebase.

**Comment by dmikushin** [comment]
Well, I rebased by hand, going though all of your 50 commits one by one) Also enforced in favor of your encoding() approach instead of mbcs.

**Pull request closed without merging**
