### PR TITLE
speech-dispatcher v0.11 changed modules location

### PR DESCRIPTION
**Pull request by turbo-cafe**
compatible with speech-dispatcher v0.11

### CODE REVIEW

**Comment by CyberTailor** [comment]
I have a "Pending" review comment.

**Comment by CyberTailor** [comment]
I'll comment here because reviews are broken.

Change `lib` to `${CMAKE_INSTALL_LIBDIR}`.
Also add `include(GNUInstallDirs)`

**Comment by alex19EP** [comment]
it would be nice if the address of this folder was taken from the pkgconfig variable.

**Comment by alex19EP** [comment]
superseded by #535

**Pull request closed without merging**
