### PR TITLE
translations of F-Droid descriptions (Esperanto + Polish)

### PR DESCRIPTION
**Pull request by verdulo**
I license this contribution under the terms set out in the 0BSD license.

### CODE REVIEW

**Comment by grzezlo** [comment]
Instead of 
systetyzatorem mowy 
should be
syntezatorem mowy.
Instead of
Syntetyzator mowy 
should be
syntezator mowy
(in all occurences).

**Comment by verdulo** [comment]
@grzezlo zaraz poprawię

**Comment by grzezlo** [comment]
Thanks for quick correction, but please correct also the 
pl/short_description.txt and pl/title.txt files.

**Comment by Olga-Yakovleva** [comment]
@verdulo, @grzezlo, could you please license the Esperanto and Polish translations in the app under a permissive License? If you agree, please just include the licensing comments in pl/strings.xml and eo/strings.xml.

**Comment by zstanecic** [comment]
Polish translations of the RHVoice app is my contribution. 

I’ve signed the CLA, so I thought that it is already relicensed?

**Comment by Olga-Yakovleva** [comment]
@zstanecic, it wasn't clear to me from #445 who was the translator. OK, could you just add the copyright or author comment to the strings.xml file, so it's clear you are the author?

**Comment by zstanecic** [comment]
Ok,

I will add the copyright header in the strings.xml in the polish localization,

How it should be commented?

With hashes or slashes?

**Comment by zstanecic** [comment]
Btw,

There in #445 sentence states::

Coauthored by @zstanecic.

**Comment by verdulo** [comment]
@Olga-Yakovleva As [described](https://github.com/RHVoice/contrib-licensing), I added information about license to this and to my [previous merge request](https://github.com/RHVoice/RHVoice/pull/240). Can it be merged now?

**Comment by Olga-Yakovleva** [comment]
Thank you, @verdulo. To clarify for the future, only #240 needed to be licensed, because it goes inside the app itself. Metadata for F-Droid doesn't need any additional license. Again, thank you!

**Pull request merged**
