### PR TITLE
fix building android app on windows

### LINKED ISSUE #517: android: android building on windows is intermittently failing
This error persists with alpha and dev packages as known by me:
when i try to compile, i get:
1 warning generated.
  C:/RHVoice/src/android/RHVoice-core/src/main/jni/../../../../../pkg/package_client.cpp:124:22: error: use of undeclare
d identifier 'https'
                       PKG_DIR_URL,
                       ^
  <command line>:3:21: note: expanded from here
  #define PKG_DIR_URL https://rhvoice.org/download/packages-dev.json
                      ^
  1 error generated.
  make: *** [C:/Users/ninos/AppData/Local/Android/Sdk/ndk/21.4.7075529/build//../build/core/build-binary.mk:478: C:\RHVo
ice\src\android\RHVoice-core\build\intermediates\cxx\Debug\2n3z4i42/obj/local/arm64-v8a/objs-debug/RHVoice_core/__/__/__
/__/__/pkg/package_client.o] Error 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 20s
20 actionable tasks: 19 executed, 1 up-to-d

### PR DESCRIPTION
**Pull request by alex19EP**
this fixes #517

### CODE REVIEW

**Comment by alex19EP** [comment]
hmm. not wright.

**Comment by Olga-Yakovleva** [comment]
This isn't working, because it takes only one of the two changes from#518. The other one must have got lost among all those windows new line characters. But actually that one doesn't seem to work either. It builds, but doesn't seem to work at runtime: I see no voices from the Alpha, which means it uses the cached json that comes with the app. And I would like the url to be defined with quotes right away anyway. If there is no way to make it work the same way on Windows and Linux, maybe somebody knows how to code this in Gradle conditionally, finding out first if we are building on Linux or Windows.

**Comment by zstanecic** [comment]
There was my pull request, which worked from help with 

@a11cf0,

But it was rejected. 

If you require local testing before merging every voice to alpha, let’s find a solution, as not all people use linux to build android packaget, thus installing sdk on linux with only cli is not documented.

**Comment by Olga-Yakovleva** [comment]
Returning to #518

**Pull request closed without merging**
