### PR TITLE
Update pronunciation dictionary for Ukrainian voices

### PR DESCRIPTION
**Pull request by VovaMobile**
This is a  new, updated  an improved pronunciation dictionary for Ukrainian voices  of RHVoice speech synthesizer provided by Synthesizer of Ukrainian speech community (https://facebook.com/syntezator)

### CODE REVIEW

**Review by alex19EP — CHANGES_REQUESTED** [review]
I think this file should be at: data/languages/Ukrainian/userdict/src/dictionary.txt

**Comment by VovaMobile** [comment]
Yes, but I don't know how to specify this path when committing a pull requests.
I used this method to commit pull requests, but the developers moved
them to the right folders.
I used Github on web, not a client.
What can we do?

2021-03-21 1:43 GMT+02:00, Alexander Epaneshnikov ***@***.***>:

**Comment by alex19EP** [comment]
> 
> Yes, but I don't know how to specify this path when committing a pull requests. I used this method to commit pull requests, but the developers moved them to the right folders. I used Github on web, not a client. What can we do? 2021-03-21 1:43 

ok. I will do it.

**Review by alex19EP — APPROVED** [review]

**Comment by VovaMobile** [comment]
Thanks!
I commited 2 identically pull requests:
1. in RHVoice repository;
2. in Ukrainian repository.
Please tell me, which repository is better to commit request to?

2021-03-21 17:03 GMT+02:00, Alexander Epaneshnikov ***@***.***>:

**Comment by alex19EP** [comment]
> Please tell me, which repository is better to commit request to?

for now rhvoice main repo is better. but pr to the language repository is also needed. 
thanks.

**Comment by VovaMobile** [comment]
Thank You! and latest question: I updating this dictionary every week.
How often to commit new PRs?

2021-03-22 9:43 GMT+02:00, Alexander Epaneshnikov ***@***.***>:

**Comment by alex19EP** [comment]
> 
> Thank You! and latest question: I updating this dictionary every week. How often to commit new PRs?

sorry for the long answer.
I recommend waiting until a few changes have been made. or if there are urgent fixes.

**Pull request merged**
