### PR TITLE
Refactor nvda driver

### PR DESCRIPTION
**Pull request by beqabeqa473**
A massive refactoring of NVDA driver.

Minimum compatible NVDA version as of this PR is NVDA 2021.1.0
Dropped python 2 support, what means of dropping support windows versions earlier than Windows 7 Service pack 1.
No need to support older NVDA versionns than 2021.X because users can easily upgrade their installations.\Removed converters to ssml and replaced them with NVDA's builtin converter.
It should not make any difference for users, but testing is needed anyway.

### CODE REVIEW

**Comment by zstanecic** [comment]
Hi @beqabeqa473 
I have tested your Pr on the stable version of NVDA, as well as on latest  alpha based on python 3.11. 
NVDA addon works without a difference without errors and issues.

**Comment by zstanecic** [comment]
edited the previous comment. Found one issue by thorough testing.

**Comment by beqabeqa473** [comment]
@zstanecic please re-test

**Comment by zstanecic** [comment]
Okay, driver is now working when it comes to voices:
Another thing which is not working are voice profiles.
Steps to reproduce:
1. install two voices: for example: natan for polish and Anna for russian, or SLT for english and anna for russian, and create the voice profile in the configuration file.
2. voice profile appears, but the switching doesn't occur.
To verify this, i have used the following  simple test:
latin: testing
cyrillic: тестирование
Even when pressing letters on the keyboard, the switch from cyrillic to latin doesn't occur.
Note: for this error, there is no log snippet.
I thing that it should issue a LangChangeCommand in this situations, but i am not sure.

**Comment by beqabeqa473** [comment]
@zstanecic Fixed voice switching when using profiles. I think we are done with it.

**Comment by beqabeqa473** [comment]
The problem was that NVDA always needs a language to correctly form an ssml string. By default, we are not able to skip this, and if default language is set for example to en-us with slt, RHVoice ignores all other languages because xml attribute instructs engine to use only en-us voice.
I've modified SsmlConverter a bit to not include xml:lang attrib in the ssml string, but this also happens when auto language switching is enabled. Ssml puts xml:lang attribute to voice tag.
@Olga-Yakovleva What would be the correct case here?

**Comment by Olga-Yakovleva** [comment]
Sorry, I don't really remember the details from writing all that synthesizer driver code quite a long time ago. So I may not be understanding correctly. My preference would be to set the lang attribute if this information comes from NVDA's language detection, I assume mostly from lang attributes on web pages. But in other cases let the profile handling work in the core without the lang attribute. Is that possible? And what is the behaviour in the old addon? I know I wrote it, but I can't remember,

**Comment by Olga-Yakovleva** [comment]
My other request to both of you is to find some more people to test the addon. There will be some updates to the core soon and a new release, 1.14.0. We are going to release the first of the voices we are working on in an international project with various organizations involved, so I'm not going to risk merging such a major rewrite shortly before this event. But when I have confirmation from more extensive testing, I will merge it for a later release.

**Comment by beqabeqa473** [comment]
In the old implementation, lang was not set at all when autolanguage was off, and it was set only if it is available and first voice of profile didn't  contain the same lang from the response of the langChanged command of NVDA. I will match that behaviour to not break users expectations

**Comment by Olga-Yakovleva** [comment]
Ok, thanks!

**Comment by beqabeqa473** [comment]
I think I'm done with it.

@zstanecic Please test it and write a feedback here.
as @Olga-Yakovleva said, It will need to be tested by more people.

**Comment by zstanecic** [comment]
Hi @Olga-Yakovleva 
and @beqabeqa473 
Automatic language switching and voice profiles are now working.

**Comment by ChrisDuffley** [comment]
Hi all,

@zstanecic/@beqabeqa473: How do I compile with SCons for this project so I can test? I only know how to do it with NVDA add-ons themselves.

Take care.

**Comment by zstanecic** [comment]
Hi @ChrisDuffley 
If you want to test the driver with the existing voices installed,
please get it from here:
https://disk.yandex.com/d/txeqKb8MC-jEgg

**Comment by zstanecic** [comment]
Feedback from the testers on my side:
My testers feel the increase in speed and responsiveness compared to the previous version. 
Nobody detected any bug in the driver yet.
@ChrisDuffley 
You are invited to test this thoroughly as you can.

**Comment by zstanecic** [comment]
Hi to all!
@beqabeqa473 
@Olga-Yakovleva 
All testers on my side don't report any bugs.
So, implementation is bug free.
@ChrisDuffley 
Do you see any bugs?

**Comment by beqabeqa473** [comment]
I still need to decouple RHVoice wrapper in its own module and write a high-level wrapper to be exposed and used by nvda and other python software, but i think this will be in subsequent pr.

**Comment by sevapopov2** [comment]
Hi all. I tested the version of the driver provided here and I didn't find any bugs as others, driver works faster now, there is absolutely no Delay noticed! Thank you!

**Comment by Olga-Yakovleva** [comment]
I want to merge this soon. But I'd like a confirmation of one point. Has anyone confirmed that it works on the minimum cmpatible NVDA version declared?

**Comment by zstanecic** [comment]
Hi Olga,
I can confirm that it works on minimum compatible version declared.
Tested it on a Vm.

**Comment by zstanecic** [comment]
btw, it will be good to change the lat tested version to 2024.1 before merging...

**Comment by Olga-Yakovleva** [comment]
@beqabeqa473, could you update the last tested version?

**Comment by beqabeqa473** [comment]
Hello.

Yes, will do this tomorrow.

On 1/14/24, Olga Yakovleva ***@***.***> wrote:
> @beqabeqa473, could you update the last tested version?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/pull/808#issuecomment-1890871760
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Pull request merged**
