### PR TITLE
Android: missing translations of version.

### PR DESCRIPTION
**Pull request by Olga-Yakovleva**
This adds Ukranian, Portuguese, Kyrgyz and Esperanto translations. The
Ukrainian translation comes from a native speaker. The rest come from
Google Translate. I'm waiting for a confirmation or correction from a Kyrgyz speaker
and a Portuguese speaker I know. I don't know anyone to ask about
Esperanto. So I'm not merging this just yet. Confirmations or
corrections from people
speaking the languages will be appreciated.

### CODE REVIEW

**Comment by zstanecic** [comment]
Hi Olga and all,
In my opinion, i think that we will need to communicate with the people on mailing list.

**Comment by Olga-Yakovleva** [comment]
Google got it right with Portuguese. So I'm going to wait for a day for an answer from someone in the mailing list and merge anyway, because a week remains before we need a public release out there.

**Comment by zstanecic** [comment]
I wrote to the Iskender Sultanaliev on twitter. I know that he worked to make the kyrgyz a reality along with you. I will reply as soon as i get the reply on twitter.

**Comment by zstanecic** [comment]
Unfortunatelly, i haven't got the answer. As there is no feedback, let's merge this.

**Pull request merged**
