### PR TITLE
Setup environment script

### PR DESCRIPTION
**Pull request by DarkoMilosevic86**
Added setup environment script for installing all necessary components for building new voices for RHVoice.

This script includes installing all necesssary packages, Festvox Speech Tools, Festival, Praat, SPTK, HTK, HTS, and RHVoice building with dev=True flag.
I am licensing this contribution using GPL-3 license.

	new file:   src/scripts/general/setup_environment

### CODE REVIEW

**Comment by Olga-Yakovleva** [comment]
Thank you, @DarkoMilosevic86. I have three suggestions:

1. Include debian in the file name, so it's clear this will only work for the Debian family of Linux distros.
2. Why /tts? I use it in my personal setup, and I may have quoted it somewhere, but in general it would require running as root or changing permissions. I suggest giving the user the ability to choose where to install from command line. And...
3. Generate training.cfg with the right paths as the final step.

**Comment by zstanecic** [comment]
Hi Olga,

You don’t need to run as root if you want to have the tts as the path. Your path can be: $username/tts/whatcomesnext

**Comment by beqabeqa473** [comment]
Anyway,, it would be more flexible to ask where to install at first.

On 5/7/23, Zvonimir Stanečić ***@***.***> wrote:
> Hi Olga,
>
> You don’t need to run as root if you want to have the tts as the path. Your
> path can be: $username/tts/whatcomesnext
>
>
>
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/pull/736#issuecomment-1537430771
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by DarkoMilosevic86** [comment]
Thank you @Olga-Yakovleva @beqabeqa473 and @zstanecic I will make changes to the script to ask for the installation path, and to regenerate training.cfg to the new paths.
And, will reopen the pull request again.

**Comment by Olga-Yakovleva** [comment]
My apologies for the incorrect /tts comment: I didn't read carefully enough.

**Pull request closed without merging**
