### PR TITLE
codeql: fix python check

### PR DESCRIPTION
**Pull request by alex19EP**

### CODE REVIEW

**Comment by zstanecic** [comment]
What's up with this? Macedonian voice pull request tries to be checked

**Comment by alex19EP** [comment]
> Macedonian voice pull request tries to be checked

it's impossible. i disabled codeql for now.

**Comment by zstanecic** [comment]
See the status check. It hangs.

**Comment by zstanecic** [comment]
Will this ever be fixed or it has the resolution wontfix?

**Pull request closed without merging**
