### PR TITLE
Colab/Jupyter notebook to create voices for RHVoice interactively in the cloud, based in Wiki

### PR DESCRIPTION
**Pull request by rmcpantoja**
This notebook can be used via [Jupyter Notebook](http://jupyter.org/) (in local) or via [Google Colab](http://colab.research.google.com/) (through machines in the cloud).

This notebook was created for the purpose of making the voices more interactive so that we can run these required steps instantly. [Test it in colab!](http://colab.research.google.com/github/rmcpantoja/RHVoice/blob/master/src/notebooks/RHVoice_training.ipynb)

## license

I license this contribution under the terms set out in the [Unlicense](https://spdx.org/licenses/Unlicense.html) license.

### CODE REVIEW

**Comment by rmcpantoja** [comment]
>I license this contribution under the terms set out in the Unlicense license.

**Comment by ZachB100** [comment]
Hey man, thanks so much for this notebook. For the most part everything was working up until I had to change the model settings. When I press run, I get the following output.
"Traceback (most recent call last):
  File "../RHVoice/src/scripts/general/voice-building-utils", line 1720, in <module>
    args.func(args)
  File "../RHVoice/src/scripts/general/voice-building-utils", line 166, in __call__
    params=self.get_configure_params()
  File "../RHVoice/src/scripts/general/voice-building-utils", line 155, in get_configure_params
    params.update(self.get_analysis_params())
  File "../RHVoice/src/scripts/general/voice-building-utils", line 110, in get_analysis_params
    params["BAPORDER"]=len(self.get_filter_band_edges())
  File "../RHVoice/src/scripts/general/voice-building-utils", line 139, in get_filter_band_edges
    nyq_freq=sr//2
TypeError: unsupported operand type(s) for //: 'str' and 'int'"
How do I get around this?

**Comment by rmcpantoja** [comment]
@ZachB100 It seems to me that this is due to the sampling rate or is it an internal error of the script that is executed (voice building utils) Can you give me your settings please? Maybe something is wrong in your training.cfg.

**Comment by zstanecic** [comment]
And, which settings you have changed? Note that not all sample rates are supported.

**Comment by ZachB100** [comment]
I was just following all of the steps in the notebook exactly. I change the parameters using the pop-up menus next to each one, I did not edit the training.cfg file. I'm guessing this is some internal error that is out of our control, so in that case is there a way to get an older version of RH that doesn't exhibit this behavior? All of the steps before this were successful, this is the only part where I'm getting stuck.

**Comment by rmcpantoja** [comment]
@ZachB100 Sorry my bad. It's an internal error that I just fixed. In the settings cell, below it press the show code button, go to the code editor and replace this line

>!jq --arg pwd "/content/tts"  '.wavedir=$pwd+"/wav"|.speaker="$speaker_name"|.language="$language"|.gender="$gender"|.sample_rate="$sample_rate"'  training.cfg >training2.cfg &&mv training2.cfg training.cfg

Replace it with:

>!jq --arg pwd "/content/tts"  '.wavedir=$pwd+"/wav"|.speaker="$speaker_name"|.language="$language"|.gender="$gender"|.sample_rate=$sample_rate'  training.cfg >training2.cfg &&mv training2.cfg training.cfg

**Comment by ZachB100** [comment]
Awesome, thank you so much, that was fast :-). I'll give this a shot and let you know how it goes. I'm really excited, I've mostly only messed with machine learning-based text to speech training, so I'm curious to see what HTS will produce. When trained in Colab, is it possible to create an NVDA add-on from there, or would I have to modify the exported model on a Windows system for that to happen? I'm really new to all of this, so sorry for all the questions lol. Thanks again!

**Comment by rmcpantoja** [comment]
Yes, an NVDA addon can be created via colab, and it is possible with SCons after exporting the voice. I think for now you'll have to download your voice data manually. I will add support for saving RHVoice work to Drive in the future and you won't have to worry, although the downside is that you would need a lot of space, it depends on the size of the dataset.

**Comment by ZachB100** [comment]
All right, so I was able to get past the model settings with no problem, however when attempting to guess F0 range I get this.
"/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:222: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:254: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "../RHVoice/src/scripts/general/voice-building-utils", line 1720, in <module>
    args.func(args)
  File "../RHVoice/src/scripts/general/voice-building-utils", line 894, in __call__
    min_f0=int(numpy.round(numpy.exp(m-d)))
ValueError: cannot convert float NaN to integer"

**Comment by rmcpantoja** [comment]
@ZachB100 I think the range f0 of your dataset cannot be identified. That being the case you can manually set the range to training.cfg. You could try with a minimum of 110, a maximum of 280

**Comment by ZachB100** [comment]
OK I see. I'll try Setting it manually to see what happens. I might also
first try a different data set, maybe SLT since that was what was used for
the tutorial. Hey, if nothing else I'm learning a lot about HTS through
this process lol.
Thanks for your help!

**Comment by ZachB100** [comment]
Ok, I tried again with SLT but got the same result. It seems like there's
an error somewhere in the code, but I'm not sure where that would be. I
unfortunately am unable to continue until this can be fixed. I am thinking
of trying to just make my own notebook from scratch following the tutorial
to figure out whether it's an issue with the notebook or Rh voice itself.

**Comment by zstanecic** [comment]
Hi,

When running all datasets with pyworld or with the old training methods, I don’t experience the issue.

I will need the questioned dataset to examine the situation.

**Comment by zstanecic** [comment]
It can be probably due to missed configure script.

Anyway, as I said, I will need the dataset to examine.

**Comment by ZachB100** [comment]
Link to data is here.
http://festvox.org/cmu_arctic/cmu_arctic/packed/cmu_us_slt_arctic-0.95-release.tar.bz2
Could you describe the steps you're going through in the notebook, as it's
entirely possible I'm missing something. As I said, I'm still really new to
all of this.
Thanks so much!

**Comment by ZachB100** [comment]
Hey, I partly figured out what was wrong with the notebook. In the step
where your configuring model settings, you should take a look at the code,
as the version you gave me is incorrect. I can't really remember what I did
to change it, but I followed the tutorial and modified slightly. I would
recommend taking a really close look and making sure you have it exactly as
in the tutorial. After the step was completed successfully, I was able to
do The F0, LF0, Bap, and MGC Analysis without issue, however when
reesynthesizing the audio Collab became very slow and my computer nearly
crashed. I would recommend removing this step from the notebook for now.
After this, I ran into another roadblock. The SSML code is also incorrect
and needs to be looked at, I tried to fix it but wasn't able to. There's an
issue with %%writefile, Colab kept throwing an error at me saying that it
wasn't a valid command or something like that.

**Comment by zstanecic** [comment]
Hi,

The code should be good, as in the tutorial there should be standard linux commands.

**Comment by ZachB100** [comment]
Yeah, I think the code is fine, I was just referencing the notebook which
needs to be updated as some of the code in there is wrong.

**Comment by ZachB100** [comment]
Hey man, thank you so much for all the time and effort you're putting into
this, I really appreciate it. I am using official Colab. I would definitely
recommend going back and trying the notebook yourself, I'm sure you'll
probably be able to fix more errors than I have. I was able to fix a few
things, but to be honest I'm not totally sure what I'm doing when it comes
to this stuff lol. Thanks again, and can't wait to try this out for real!

**Comment by rmcpantoja** [comment]
@ZachB100 Thank you for your words! And yes, I tried to fix a lot of errors in the notebook recently, but I do not guarantee that it works correctly. I have been training a Jack the Ripper dataset and I have had some errors in the "labelling" part, but it must be because of my dataset or because there are badly set paths. As I say, I would be needing more testers for this notebook to be able to work better on bug fixes.

**Comment by ZachB100** [comment]
Hey man, that's awesome. I'm about to try it and will let you know what I
find. I definitely agree that more people should be testing this, I'm
surprised a notebook like this didn't already exist, as I'm sure a lot of
people would like to try their hand at creating custom voices for RH.
Why don't you post this over on discussions to get more eyes on it, I
imagine there would be a lot more people looking at that who would be able
to test and make sure everything is working correctly. I of course am happy
to help in any way I can. Thank you again, and I'll keep you updated.

**Comment by ZachB100** [comment]
All right, here's a quick update.
The notebook is working much better now, however like you said I'm having
issues with the labeling part. It simply refuses to do it, complaining that
there is no tmp file, and I cannot move forward with the training process.
Also, in the model settings, I would double check the code, as the
variables you have set for filling in the training.CFG are not being
applied correctly.
With that being said, we are almost there. Thanks again, and hopefully this
can be fixed soon!

**Comment by ZachB100** [comment]
OK, here's another quick update. I tried again using the SLT data set, and
another festival data set as well, and when configuring the SSML files and
generating the labels, I got the following error after about 10 to 15
minutes. "  ERROR [+6510]  LOpen: Unable to open label file
htk/mfcc/RHVoice_Test_0096.lab
 FATAL ERROR - Terminating program /content/tts/htk341/bin/HERest
Traceback (most recent call last):
  File "../../../tts/RHVoice/src/scripts/general/voice-building-utils",
line 1720, in <module>
    args.func(args)
  File "../../../tts/RHVoice/src/scripts/general/voice-building-utils",
line 689, in __call__
    n=self.reest_until(n,3,0.001,max_reest_iter)
  File "../../../tts/RHVoice/src/scripts/general/voice-building-utils",
line 493, in reest_until
    self.reest(i,j)
  File "../../../tts/RHVoice/src/scripts/general/voice-building-utils",
line 487, in reest

self.hrun("HERest","-C",self.param_conf_path,"-I",phmlf,"-t","250.0","150.0","1000.0","-S",self.mfcc_scp_path,"-H",os.path.join(indir,"macros"),"-H",os.path.join(indir,"hmmdefs"),"-M",outdir,phlist,tag=str(i))
  File "../../../tts/RHVoice/src/scripts/general/voice-building-utils",
line 360, in hrun
    subprocess.check_call(cmd,stdout=f)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/content/tts/htk341/bin/HERest',
'-D', '-A', '-T', '3', '-C', 'htk/param.conf', '-I', 'htk/phones3.mlf',
'-t', '250.0', '150.0', '1000.0', '-S', 'htk/mfcc.scp', '-H',
'htk/hmm/22/macros', '-H', 'htk/hmm/22/hmmdefs', '-M', 'htk/hmm/23',
'htk/phonelist']' returned non-zero exit status 110.
Labelling...
# Generating monophone and fullcontext Master Label Files (MLF)
echo "#!MLF!#" > labels/mono.mlf
echo "\"*/RHVoice_Test_*.lab\" ->
\"/content/drive/MyDrive/rhwork/data/labels/mono\"" >> labels/mono.mlf
echo "#!MLF!#" > labels/full.mlf
echo "\"*/RHVoice_Test_*.lab\" ->
\"/content/drive/MyDrive/rhwork/data/labels/full\"" >> labels/full.mlf
# Generating a fullcontext model list file
mkdir -p lists
rm -f tmp
for lab in labels/full/RHVoice_Test_*.lab; do \
if [ -s ${lab} -a -s labels/mono/`basename ${lab}` -a -s cmp/`basename
${lab} .lab`.cmp ]; then \
sed -e "s/.* //g" ${lab} >> tmp; \
fi \
done
/bin/sh: 2: [: cmp/RHVoice_Test_0001.cmp: unexpected operator
sort -u tmp > lists/full.list
sort: cannot read: tmp: No such file or directory
Makefile:282: recipe for target 'list' failed
make: *** [list] Error 2
Traceback (most recent call last):
  File "../../../tts/RHVoice/src/scripts/general/voice-building-utils",
line 1720, in <module>
    args.func(args)
  File "../../../tts/RHVoice/src/scripts/general/voice-building-utils",
line 711, in __call__
    subprocess.check_call(["make","list"])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'list']' returned non-zero
exit status 2."
Could someone who knows a little more about how HTS and festival works
chime in here and tell me what I am doing wrong? I am following the
tutorial exactly, at least as far as I am aware.
Thanks.

**Comment by ZachB100** [comment]
Hey, great news! I was finally able to get the voice to train, I simply
needed to turn on the silence detection as explained in the tutorial. After
doing this, the segmentation and labels were created successfully. I now
have two remaining issues. First, when resynthesizing the audio and testing
the subsequently trained voice, I am only getting very loud beeps with no
audible speech. My sample rate is at 24,000Hz, and I am using the SLT
dataset. Additionally, I am unable to create an NVDA addon from the trained
voice. Packages are only being exported to work on Linux as far as I can
tell. If I could get help with both of these issues that would be massively
appreciated. Thank you so much!

**Pull request closed without merging**
