### PR TITLE
updated emoji data to 39.0

### LINKED ISSUE #312: update CLDR to the latest version
Hi to all,
This is specially interesting for 
@alex19EP 
and
@Olga-Yakovleva 
I have prepared the pull request whic updates the submodule of the unicode CLDR data to the latest version.
In that way, RHvoice emoji support will be the same as we have it directly included in NVDA.
From this change, mostly benefits all android devices running RHVoice and also the linux platform.
What do you think? 
Best,
Zvonimir

### PR DESCRIPTION
**Pull request by zstanecic**
Emoji data updated, fixes #312 
Changed the submodule to 39.0,
ran the import emoji script,
emojidata.cpp was updated accordingly, as scripts updates it automatically,
changed language info to reflect new changes for each language,
Compiled locally and verified that it works properly.

### CODE REVIEW

**Comment by zstanecic** [comment]
in the commit message, it's 39.0, not 30.0

**Comment by zstanecic** [comment]
Note 2: all people who follows the repo will need to run git submodule update,
thanks

**Review by alex19EP — CHANGES_REQUESTED** [review]
need to clear your commit history.

for the future, can you create pr not from the master branch?

**Comment by zstanecic** [comment]
Hi, it's too difficult. It's better for me to merge master to master, if the change is small like this. I will apply changes as soon as possible.

**Comment by alex19EP** [comment]
> 
> 
> Hi, it's too difficult. It's better for me to merge master to master, if the change is small like this. I will apply changes as soon as possible.

I fixed it for you, but you will have to reset your branch after I merge this pr.

**Comment by zstanecic** [comment]
Ok. How can i reset it?

**Review by alex19EP — APPROVED** [review]
ok now all is good.

ready to merge!

**Comment by alex19EP** [comment]
> 
> 
> Ok. How can i reset it? Note that i have linked upstream to my fork.

execute this in your terminal.
```bash
git fetch upstream
git reset --hard upstream/master
git push -f
```

next time before starting work on a new feature, create a new branch
`git switch -c new-feature`
and then make your changes. then just post your branch
`git push --set-upstream origin new-feature`

now there will be a button in the github interface to create a pr.

p.s. if you want I can call you and will teach you how to do all this.

**Comment by zstanecic** [comment]
Thanks. Done. I will let myself know when updating in the future.

**Pull request merged**
