### PR TITLE
Community changes from NLProc.by

### PR DESCRIPTION
**Pull request by abitrolly**
NLProc.by and Minsk Hackerspace community changes.
- Python CLi interface - https://pypi.python.org/pypi/RHVoice
- Continuous integration for OS X, Linux and Windows
- OS X compilation fixed
- Partial Debianization

### CODE REVIEW

**Comment by beqabeqa473** [comment]
hello.

after testing several major issues were found.

1. nvda plugin doesn't work anymore, error message is   File "C:\Users\admin\AppData\Roaming\nvda\addons\RHVoice\synthDrivers\RHVoice\__init__.py", line 23, in <module>
ImportError: cannot import name RHVoice_lib_path

2. only english texts work for now, i can't process russian texts however file is encoded in unicode.


thanks

**Comment by abitrolly** [comment]
@beqabeqa473 thank you for the feedback. The error message should be fixed, but we can not test NVDA. Can you try again?

**Comment by beqabeqa473** [comment]
yes, first error is fixed.

as for other text not speaking, i think you are hardcoding first english voice, because of this others don't work.

please, if you can, add commandline parameters to controll the engine, adjust rate, pitch, voice, select voices etc.

thanks.

**Comment by abitrolly** [comment]
@beqabeqa473 yes, these things are hardcoded right now. The point is to merge this minimal viable interface and enable other people to improve it. As you see, the first commit was made on Feb 9 and there is a huge probability that there won't be much free time to polish the thing.

**Comment by abitrolly** [comment]
@beqabeqa473 parameters to select voice, rate, pitch and volume are added. Automatic detection of data/ directory is also there. Check this out. =)

**Comment by beqabeqa473** [comment]
yep, thanks, i've already checked it several days ago.

one more suggestion, if it is possible to make python cli to output speech directly to sound card in addition to writting a wave file.

**Comment by abitrolly** [comment]
@beqabeqa473 yes it is possible, but not in this pull request, because it is a pretty sophisticated piece of code.

**Comment by beqabeqa473** [comment]
what should be done else to complete python cli?

**Comment by abitrolly** [comment]
@beqabeqa473 nothing. Just merge this so that it won't be lost/go out of sync.

In the long term the thing that should be done is to find some money, which buy time to produce and review the code. Then it will be possible to:

1. move from ctypes to CFFI (automatic validation C-like interface declarations)
2. measure memory leaks and performance
3. move Python module into separate directory
4. update SConstructs
5. build .so for Linux and OS X and package Python wheel there
6. add direct output to soundcard on Windows
7. add direct output to soundcard on Linux
8. add direct output to soundcard on OS X
9. compile for PNaCl

10. **add more voices**
11. add documentation about how to build a voice
12. add tube resonance model (TRM) acoustic model from gnuspeech
13. add diagrams

More? :)

**Comment by zstanecic** [comment]
Этот пул риквест конфликтует. Закройте его

**Comment by abitrolly** [comment]
@zstanecic or rebase and solve conflicts?

**Comment by alex19EP** [comment]
@abitrolly can you fix conflicts?

**Comment by abitrolly** [comment]
@alex19EP that might be tough, but let me try it.

**Comment by abitrolly** [comment]
@alex19EP as I expected it didn't work out - I couldn't rebase it past merge commits. I asked @techtonik to rebase his https://github.com/Olga-Yakovleva/RHVoice/pull/34 first, because this one is based on top of his.

**Comment by alex19EP** [comment]
ok will wait for @techtonik  comments.
thanks

**Comment by zstanecic** [comment]
Hi,
My opinion on this is to close this, as this is over outdated.

**Pull request closed without merging**
