### PR TITLE
Emoji data: updated to 40.0

### PR DESCRIPTION
**Pull request by zstanecic**
Updates emoji to 40.0 * in alpha, but works and tested accordingly,
Updated languages:
brazilian portuguese,
english,
georgian,
Kyrgyz,
macedonian,
russian,
ukrainian
Tatar and esperanto never supported emoji, so i've skipped this.
Script took care of emoji.cpp, so it's Ok.
Emoji data used was:
https://unicode.org/Public/14.0.0/ucd/emoji/emoji-data.txt
2021-08-26 14:49
cc
@alex19EP 
@Olga-Yakovleva 
Any thoughts?

### CODE REVIEW

**Comment by alex19EP** [comment]
lets Waite for proper cldr release.

**Comment by zstanecic** [comment]
Should i convert it to draft and work on it, i.e follow the progress of the cldr dev?

The cldr release is expected to be released on the sep 14.

**Comment by alex19EP** [comment]
yes. thank you.

**Comment by zstanecic** [comment]
This pull request is readi for merging. Unicode 40 has been released yesterday, along with the emojidata.txt

**Comment by zstanecic** [comment]
What to do? windows build fails on the server?

**Comment by alex19EP** [comment]
> What to do? windows build fails on the server?

yep. I need to fix hour CI. then I will merge this.

**Comment by zstanecic** [comment]
I am going to push the latest changes from the cldr maintenance branch. It will not affect the synthesizer

**Comment by alex19EP** [comment]
please increment version of changed languages

**Review by alex19EP — CHANGES_REQUESTED** [review]
please increment version of changed languages

**Comment by zstanecic** [comment]
What with our Ci?

**Comment by alex19EP** [comment]
> What with our Ci?

it isn't working at the moment.

**Review by alex19EP — APPROVED** [review]
I fixed all remaining issues and will merge this.

**Pull request merged**
