### PR TITLE
Gradle Paralell Builds & Docs improvements

### PR DESCRIPTION
**Pull request by qkqsb**
new file:   doc/en/Compiling-for-Android.md
modified:   doc/en/Configuration-file.md
modified:   src/android/gradle.properties
Added gradle paralell builds. See link for more info:
https://docs.gradle.org/current/userguide/performance.html#parallel_execution

### CODE REVIEW

**Comment by zstanecic** [comment]
Hi,
Why the file Configuration-file.md is modified?

**Comment by qkqsb** [comment]
Zvonimir,

I added more documentation to clearly explain how the configuration file is used on android.

**Comment by zstanecic** [comment]
Okay,

In that case it is ok.

**Comment by Olga-Yakovleva** [comment]
@qkqsb, could you help fix the reason #714 fails to build? I don't know Gradle well enough to know how to debug and fix this.

**Pull request merged**
