### PR TITLE
Creating new voice tutorial

### PR DESCRIPTION
**Pull request by grzezlo**
Tutorial describing in detail new voice for RHVoice creation process. Some questions still open.

### CODE REVIEW

**Comment by alex19EP** [comment]
First of all, thank you for this work, it's really cool. I think the best place for this kind of document is our wiki.

**Comment by grzezlo** [comment]
Hi, thanks for the positive feedback.
If I understand well, the wiki was deleted fewmonths ago, and all knowledge is collected in the doc folder.

**Comment by alex19EP** [comment]
I reenabled the wiki now.

we have moved documentation that was written by the RHVoice developers and does not require frequent updates. for information like this document, I think the wiki is the best place.

**Comment by grzezlo** [comment]
I cloned the wiki, and it's empty.
Also no pages are visible after clicking "Wiki" link on the RHVoice Github website.
And, last but not least, have a look at issue 315, where  the wiki was intentionally cleaned and disabled. 
Sorry, but I'm a bit confused now.. Will the RHVoice/doc directory be moved to the wiki in future?
https://github.com/RHVoice/RHVoice/issues/315

**Comment by alex19EP** [comment]
> I cloned the wiki, and it's empty. Also no pages are visible after clicking "Wiki" link on the RHVoice Github website.

you can create *.md files and they will be available on the wiki.

> And, last but not least, have a look at issue 315, where the wiki was intentionally cleaned and disabled. Sorry, but I'm a bit confused now.. Will the RHVoice/doc directory be moved to the wiki in future? #315

sorry for confusion. I'll try to explain. when I moved documentation from wiki to doc / Olga and I decided that documents that are directly related to RHVoice and do not require frequent updates will be stored in doc / and any guides from the community that need to change quickly and which may have several authors will be posted on the wiki.

I think this is quite convenient.

**Comment by grzezlo** [comment]
Now it became really complicated.
1. I added the file to my rhvoice.wiki clone and committed.
2. I can not push - error 403.
3. I have clone of main RHVoice repo, but can not clone the wiki to be able to push something in my fork, and then create pull request.
4. Clicking "New page" in main RHVoice wiki has no effect.
No more ideas how to accomplish this simple task.

**Comment by alex19EP** [comment]
> Now it became really complicated.

I enabled push on the wiki now it should work.

sorry.

**Comment by grzezlo** [comment]
Push not worked: remote: Permission to RHVoice/RHVoice.wiki.git denied to grzezlo.
But editing via website started to work, so I did it this way.

**Pull request closed without merging**
