### PR TITLE
Added Macedonian voice Suze

### PR DESCRIPTION
**Pull request by gerazov**

### CODE REVIEW

**Comment by zstanecic** [comment]
@gerazov 
In the voice info file, please add two parameters: msi_upgrade_code
and
exe_upgrade_code.
After the equals sign, you need to put the guid for the installer.
You can create one by this tool:
https://www.guidgenerator.com

**Comment by zstanecic** [comment]
I suggest the following change:

In the voice_info file:

Exe_upgrade_code=c3a71985-b8fb-412b-be9d-55b8ad8d7aa6

Msi_upgrade_code=fdff2fb4-1989-4d4f-93bf-afa787744f57

This step fixes the pull request build which fails intermittently. 

Next, please edit the voice_params file and add the key parameter:

Example: key=150

You should see the median pitch of your created voice, this is just the example

This parameter enables the exclamation intonation and interrogative sentence intonation.

Hope it helps,

Zvonimir

 

From: Branislav Gerazov ***@***.***> 
Sent: Tuesday, March 15, 2022 4:14 PM
To: RHVoice/RHVoice ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RHVoice/RHVoice] Added Macedonian voice Suze (PR #506)

 

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/RHVoice/RHVoice/pull/506


Commit Summary


*	8f650b6 <https://github.com/RHVoice/RHVoice/pull/506/commits/8f650b6364c7ce29d4a324e9254df8cff2acd5a3>  added Macedonian voice Suze


File Changes 


(40 <https://github.com/RHVoice/RHVoice/pull/506/files>  files)

*	A data/voices/suze/16000/bap.pdf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-9736a9d9152d8dd243e2d555ac80a46467f9e97cd0467856a5e7670b59e679a7>  (0) 
*	A data/voices/suze/16000/bap.win1 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-e96cecc00121e19e41f40bdf97afc69b5d1858918bc76f85e48f3c1183aa95a9>  (1) 
*	A data/voices/suze/16000/bap.win2 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-81cb6f75e8bf79758cc893a4af2978871d48ec3a86fb1f92ef98b2ac53130cae>  (1) 
*	A data/voices/suze/16000/bap.win3 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-5871e35f15927b66ec0cee14d62f893fc3a97af8e3b80b468857a8831650fbd1>  (1) 
*	A data/voices/suze/16000/bpf.txt <https://github.com/RHVoice/RHVoice/pull/506/files#diff-9afb9cd9424671afa93769559a52858f0b6487e853a8425e603afa540dbf350d>  (307) 
*	A data/voices/suze/16000/dur.pdf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-76f902a1bd2df8b845e1d9b996b00ea24e5bcfc0a626b580d5a81c8393f1720c>  (0) 
*	A data/voices/suze/16000/lf0.pdf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-05da64762b68b9ffc15d54ff181c7e9d3d9e53034203d5c78479020df4f8a832>  (0) 
*	A data/voices/suze/16000/lf0.win1 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-4697502704dae3b014af992125720bc4dacd93827b3d06f7bad7204a65c48552>  (1) 
*	A data/voices/suze/16000/lf0.win2 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-afa6350cd144abad4df1bf177a819f20a88d19f288a9c2f7b7bb114361627242>  (1) 
*	A data/voices/suze/16000/lf0.win3 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-5ef209b275b4637612f4fee65545f45ad3c9797e0c7d3681cc6120c1571ff07a>  (1) 
*	A data/voices/suze/16000/mgc.pdf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-118b1c5b551786eb3ef3a9ff99c4e0e11c5d0d5a1ec707cf65933de2aeb3a018>  (0) 
*	A data/voices/suze/16000/mgc.win1 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-169abab91c4d9b25febd046e2f9ef1d58da3ebb63001c9ab616929d474d384ff>  (1) 
*	A data/voices/suze/16000/mgc.win2 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-fa87505ef12c5f0ae20d723c6a3bbd20a45ec439494b92ea75e55b97f6a471bd>  (1) 
*	A data/voices/suze/16000/mgc.win3 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-89930bec00bef36b00ba46d25ba474a3dc3a0e47975fbe69b13b0d38c78c14d3>  (1) 
*	A data/voices/suze/16000/tree-bap.inf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-60b326f04d7017b893ecce106be75a5835f8f97b1008bb52396d6de68ba9cb32>  (10967) 
*	A data/voices/suze/16000/tree-dur.inf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-f7b41c1e999a18e5cedd2e9576c9d0cc6e4d0d02b169598b6b52c0eee63d2349>  (2177) 
*	A data/voices/suze/16000/tree-lf0.inf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-3b9ff051f2e9d403014527784326ed54b2bf2860fe2aecad3e2320c91a7445df>  (12115) 
*	A data/voices/suze/16000/tree-mgc.inf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-cf8f1d9e8aa6f7447d96a069d60f6d8bcf39516a55d922075a65e4705789bcda>  (4453) 
*	A data/voices/suze/16000/voice.data <https://github.com/RHVoice/RHVoice/pull/506/files#diff-854488fbb9209a10e4e67748a3968ceea423cdf35c8066ee9ee790cff2b695fc>  (0) 
*	A data/voices/suze/24000/bap.pdf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-d8988dd9e56c95365eb61fdb6aad0f956cc4ae95ba3d6e625da61508a0f98e03>  (0) 
*	A data/voices/suze/24000/bap.win1 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-a1f3ee433813ab0d36cffe1a85398e6cdc65278db4282d6a7c74f3f1b599ddbe>  (1) 
*	A data/voices/suze/24000/bap.win2 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-d3587e4cb983125c457fbc278d69b02b582d6dde0ff2d5e2abce13c18ad4c1b4>  (1) 
*	A data/voices/suze/24000/bap.win3 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-85a13f39a272ebf734288742a479242b9a4becf47d71ab09dea3a7e960b72457>  (1) 
*	A data/voices/suze/24000/bpf.txt <https://github.com/RHVoice/RHVoice/pull/506/files#diff-16fecf5c12108018e1ba27acd1a44539e07d3d509c2764a27403a9a7959169f8>  (625) 
*	A data/voices/suze/24000/dur.pdf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-c13dbbf99cd6e4a532380831a36e560f5e6c220b206f5b77d37c56cf7e55546c>  (0) 
*	A data/voices/suze/24000/lf0.pdf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-74ddfaa4efa51a2a13c14256a129c71906154255eb03a5d39df45ccde6a5ef2a>  (0) 
*	A data/voices/suze/24000/lf0.win1 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-7b7de4284671f574ee3e6dc242860bf851daf7b933e367372b554d872c6ba1a1>  (1) 
*	A data/voices/suze/24000/lf0.win2 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-83b3998e898a6cc30e6607ec40eb25a400ee8ff47159fd7ee74e96c02c921be7>  (1) 
*	A data/voices/suze/24000/lf0.win3 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-93c4a8a95b57565818c14e340ca2c781d613cac2d88338a08897ab522aa7248a>  (1) 
*	A data/voices/suze/24000/mgc.pdf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-abc793f9d5ef022a5930054829bb8da7d686848cc2ad08c10fce6f2a1497c4c1>  (0) 
*	A data/voices/suze/24000/mgc.win1 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-e34812f22f03c77ea2a84f4c4d9a6cb93389ce0928671ff13dcdaa5071805281>  (1) 
*	A data/voices/suze/24000/mgc.win2 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-e724b1d3031d428043bebe62959eefc52b7e58c6e1dec0c4bf29d91551051661>  (1) 
*	A data/voices/suze/24000/mgc.win3 <https://github.com/RHVoice/RHVoice/pull/506/files#diff-ce3be6e2abd8140b454da2156f97ffc967065595f724a0b8a52b7e4fe1243b3b>  (1) 
*	A data/voices/suze/24000/tree-bap.inf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-13093bf0cb550d1bad5f5135e4f9f60bb7dc6144685e376546989ff7423e297e>  (8540) 
*	A data/voices/suze/24000/tree-dur.inf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-3655f77f1ce2aa77bb562a1d1cf9bf2df4b1c8a006cac2cd929d802e1c40de67>  (2196) 
*	A data/voices/suze/24000/tree-lf0.inf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-a42ddf83bf207fdad020cb35772a1005cdc3a97774e638e69876dce3aa4cde99>  (12122) 
*	A data/voices/suze/24000/tree-mgc.inf <https://github.com/RHVoice/RHVoice/pull/506/files#diff-8a0c2a99e1a8e65b05389b84d1ba8b22e99d6a11274aa555a170bae51ab33501>  (4024) 
*	A data/voices/suze/24000/voice.data <https://github.com/RHVoice/RHVoice/pull/506/files#diff-ffbbdcc814e265f8c330e37b1c10c0368e0da313fb8ebea5af4b081da5e01dcc>  (0) 
*	A data/voices/suze/voice.info <https://github.com/RHVoice/RHVoice/pull/506/files#diff-6d5ae011957610220e6abaa08d4843d244fb3f8369e5c167eb839d43f405dccc>  (5) 
*	A data/voices/suze/voice.params <https://github.com/RHVoice/RHVoice/pull/506/files#diff-e84c0e2db16190aa28d49eab5318ecd5e7207fd623f064648bf4cc95ef23478a>  (2) 


Patch Links:


*	https://github.com/RHVoice/RHVoice/pull/506.patch
*	https://github.com/RHVoice/RHVoice/pull/506.diff

**Comment by maniyax** [comment]
@alex19EP, can you create a new repository for this voice?

**Comment by gerazov** [comment]
Thanks for the help :pray:

We've updated the voice files as instructed. Our median is around 180 Hz so I've used that one.

If we lower it to 150 Hz the pitch variance is reduces, which might be favorable for screen reader users. However, apparently this only affects phrase final pitch dynamics for questions and exclamations. Do you have a parameter that tones down pitch dynamics overall?

Also questions and exclamations shouldn't have such strong phrase final devoicing. Is it something that can be set via a parameter as well?

Here are the two audio files and a comparison of their intonation patterns:

https://user-images.githubusercontent.com/15214418/158548087-286b9986-31a0-4cd8-8782-e204362e2463.mp4

https://user-images.githubusercontent.com/15214418/158548108-314f8750-7eab-4b0f-9615-b2a62f0061d9.mp4


image

**Comment by zstanecic** [comment]
Median of 180 is good. There is no need to change it.

It will be good for screen reader users. I am myself one of these.

There is not the parameter for overall pitch, just one for question and exclamation patterns, as I recall it nnow.

**Comment by zstanecic** [comment]
Why this python check takes too long, even when all thinks went well?

**Comment by gerazov** [comment]
Ok I've moved the files to the `RHVoice/suze-mkd` submodule so that the voice can be added to the main repo.

Closing this.

**Comment by alex19EP** [comment]
hmm. you could just update this pr.

**Comment by alex19EP** [comment]
merged as 52440af8

**Comment by Olga-Yakovleva** [comment]
@gerazov, I've written this wiki page documenting further steps for your team: https://github.com/RHVoice/RHVoice/wiki/Publishing-a-voice

**Comment by Olga-Yakovleva** [comment]
@gerazov, could you tell me who is the copyright holder for this voice? Is it you personally?

**Comment by Olga-Yakovleva** [comment]
Actually, @gerazov, could you put some kind of short readme file in the voice directory? Saying who holds the copyright and what the license is. @zstanecic sent me an email about the license, but I'd prefer this information to publically and clearly come from the voice developer.

**Comment by zstanecic** [comment]
Branislav plans to do this soon.

We arranged this on a meeting.

**Pull request closed without merging**
