### PR TITLE
Compilation fix of android version on windows 

### PR DESCRIPTION
**Pull request by zstanecic**
Thanks to @a11cf0!
It may break linux, let's wait all checks.

### CODE REVIEW

**Comment by zstanecic** [comment]
It works!

**Comment by Olga-Yakovleva** [comment]
Could you restore the line endings back to the unix style?

**Comment by zstanecic** [comment]
How and in which file?

**Comment by alex19EP** [comment]
I already working on this.

**Comment by Olga-Yakovleva** [comment]
I've built an Alpha from this code on Linux and done a fresh install, with previous version of RHVoice removed from the device. No Polish voices.

**Comment by zstanecic** [comment]
Strange, then it should be found a fix, and or building android on linux should be documented from command line.

**Comment by Olga-Yakovleva** [comment]
A fix will be welcome.

**Comment by zstanecic** [comment]
Unfortunatelly, I don’t have more ideas to fix this.

The windows interpreter swallows these quotes.

**Pull request closed without merging**
