### PR TITLE
Replaced some http:// links to https://

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by alex19EP** [comment]
I can't push commits in this pr. can you [enable maintainer access](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

**Comment by KOLANICH** [comment]
>can you enable maintainer access?

I can, but I don't think it is right to allow to allow other people to push into my fork directly, that's why it is disabled.

What changes do you want to push? GitHub has a feature to propose changes to PRs, that can be merged by the contributor with a few clicks.

**Comment by abitrolly** [comment]
@KOLANICH have you checked if none of these links are broken?

**Comment by KOLANICH** [comment]
@abitrolly, in fact I have manually verified the patch (in fact I have created it in process of testing the software that bulk rewrites http links to https). Most of the links here are FSF contact URI and FreeDesktop. Though the patch is large, I may have missed something, independent review of all my contributions to FOSS is always encouraged.

**Comment by alex19EP** [comment]
> > can you enable maintainer access?
> 
> I can, but I don't think it is right to allow to allow other people to push into my fork directly, that's why it is disabled.

this is just one branch. sorry, but I don't see any security issues here.

> 
> What changes do you want to push? GitHub has a feature to propose changes to PRs, that can be merged by the contributor with a few clicks.

I know about it, but you can't add 1000 lines like that.

**Comment by KOLANICH** [comment]
Have splitted into 2 commits. One deals only with gnu.org as the most prevalent one, another one deals with other links.

**Comment by abitrolly** [comment]
@KOLANICH the question is - did you check that links actually return 200 status?

**Comment by KOLANICH** [comment]
There are [2 commits](https://github.com/RHVoice/RHVoice/pull/277/commits)

* https://github.com/RHVoice/RHVoice/pull/277/commits/7e23b3f0bb94d37e9f4281be1cdcdbeed8f0136c replacing `http://www.gnu.org` to `https://www.gnu.org `. The most prominent link there is https://www.gnu.org/licenses/ . It opens.
* https://github.com/RHVoice/RHVoice/pull/277/commits/51017193f0e9ee94ec5c39a1ca56e21301723611 that replaces the following links:
    * https://www.freedesktop.org/wiki/Software/pkg-config/ - opens
    * https://www.freedesktop.org/wiki/Software/PulseAudio/ - opens
    * `https://ru.wiktionary.org/wiki/{}?action=render`, i.e. https://ru.wiktionary.org/wiki/voice?action=render - opens
    * https://fsf.org/ - redirects to https://www.fsf.org/, imho OK
    That's all.

**Comment by alex19EP** [comment]
since I still can't post my commits. please apply this patch.

[0001-some-improvements.patch.txt](https://github.com/RHVoice/RHVoice/files/6274776/0001-some-improvements.patch.txt)

**Comment by alex19EP** [comment]
also i think src/third-party/ shouldn't touched by this.

**Review by alex19EP — APPROVED** [review]
LGTM thanks.

**Pull request merged**
